name 'audit_wrapper'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures audit_wrapper'
long_description 'Installs/Configures audit_wrapper'
version '0.1.0'
